spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: default-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      properties:
        spring.json.add.type.headers: false

app:
  topic:
    transactions: transactions
    validated-transactions: validated-transactions
    confirmed-transactions: confirmed-transactions

  confirm:
    delay:
      ms: 5000    # quanto spesso esegue il scheduler (ms)
    threshold:
      seconds: 5  # soglia "older than" per confermare notifiche (secondi)


logging:
  level:
    root: ERROR # Log di Spring Boot - ERROR: mostra solo gli errori, INFO: mostra anche le informazioni, DEBUG: mostra anche i dettagli di debug
    org.apache.kafka.streams.processor.internals.StateDirectory: OFF # Log di Kafka Streams - OFF: disabilita i log, ERROR: mostra solo gli errori, INFO: mostra anche le informazioni, DEBUG: mostra anche i dettagli di debug
    it.alex.kafka.banking: INFO # Log della nostra applicazione - INFO: mostra le informazioni, DEBUG: mostra anche i dettagli di debug
